### ISSUE TITLE
Calculator doesn't work on iphone browser

### ISSUE THREAD

**Issue by Kwiyos** [unoplatform/RpnCalculator#36]
I tried to host this sample on Microsoft Azure (https://xamarinwasm.z19.web.core.windows.net/calculatorsample/dist/index.html) to test on mobile device. I've tested it and it worked fine on android device and mac safari browser, the page is able to load on iphone safari/chrome as well but the buttons is not working.

**Comment by Kwiyos** [comment]
Turns out the ios version need to be 13 and above to work, closing this.

**Comment by jeromelaban** [comment]
Indeed, thanks for the report!
